### ISSUE TITLE
Axis not found

### ISSUE THREAD

**Issue by moueza** [moueza/covid19-corona-virus-scilab#25]
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/8.5.53
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Mar 11 2020 10:01:39 UTC
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 8.5.53.0
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            5.8.0-41-generic
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /home/peter/jdk1.8.0_251/jre
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_251-b08
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /home/peter/apache-tomcat-8.5.53
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/home/peter/apache-tomcat-8.5.53
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dwtp.deploy=/home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=/home/peter/apache-tomcat-8.5.53/endorsed
Feb 22, 2021 10:16:50 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Feb 22, 2021 10:16:50 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
Feb 22, 2021 10:16:50 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8088"]
Feb 22, 2021 10:16:50 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Feb 22, 2021 10:16:51 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 3104 ms
Feb 22, 2021 10:16:51 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Feb 22, 2021 10:16:51 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.53
Feb 22, 2021 10:17:02 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Feb 22, 2021 10:17:02 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid19-corona-virus-scilab/WEB-INF/lib/log4j-slf4j-impl-2.12.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid19-corona-virus-scilab/WEB-INF/lib/slf4j-simple-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/peter/workspace-spring-tool-suite-4-4.6.0.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/covid19-corona-virus-scilab/WEB-INF/lib/logback-classic-1.2.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Feb 22, 2021 10:17:03 AM com.sun.faces.config.ConfigureListener contextInitialized
INFO: Initializing Mojarra 2.2.0 ( 20130502-2118 https://svn.java.net/svn/mojarra~svn/tags/2.2.0@11930) for context '/covid19-corona-virus'
Feb 22, 2021 10:17:03 AM com.sun.faces.spi.InjectionProviderFactory createInstance
INFO: JSF1048: PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked with these annotations will have said annotations processed.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Feb 22, 2021 10:17:08 AM org.primefaces.webapp.PostConstructApplicationEventListener processEvent
INFO: Running on PrimeFaces 7.0
Feb 22, 2021 10:17:08 AM org.apache.catalina.core.ApplicationContext log
INFO: Marking servlet [AxisServlet] as unavailable
Feb 22, 2021 10:17:08 AM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet [AxisServlet] in web application [/covid19-corona-virus] threw load() exception
java.lang.ClassNotFoundException: org.apache.axis2.transport.http.AxisServlet
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1358)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:546)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:527)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1044)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:985)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4887)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Feb 22, 2021 10:17:08 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8088"]
Feb 22, 2021 10:17:08 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 17661 ms

**Comment by moueza** [comment]
https://stackoverflow.com/questions/16881444/classnotfoundexception-org-apache-axis2-transport-http-axisadminservlet
